import * as vscode from 'vscode';
import { z } from 'zod';
import { loadConfig } from '../config/config';
import { OpenAiProvider } from '../ai/openAiProvider';
import { LlmSettingsStore } from '../ai/llmSettingsStore';

const message = z.discriminatedUnion('type', [z.object({ type: z.literal('save'), baseUrl: z.string(), protocol: z.enum(['responses', 'chat-completions']), models: z.string(), apiKey: z.string().optional() }), z.object({ type: z.literal('test'), baseUrl: z.string(), protocol: z.enum(['responses', 'chat-completions']), models: z.string(), model: z.string(), apiKey: z.string().optional() })]);
export class LlmConfigPanel {
  static async open(context: vscode.ExtensionContext, root: vscode.Uri): Promise<void> { const store = new LlmSettingsStore(context.globalStorageUri); const panel = vscode.window.createWebviewPanel('sqlOrganizer.llmConfig', 'SQL Organizer: LLM Configuration', vscode.ViewColumn.One, { enableScripts: true }); const render = async (notice = '') => { const settings = await store.get(await loadConfig(root)); panel.webview.html = html(settings.baseUrl, settings.apiProtocol, settings.models, notice); }; panel.webview.onDidReceiveMessage(async (raw: unknown) => { const parsed = message.safeParse(raw); if (!parsed.success) return void vscode.window.showErrorMessage('Rejected invalid LLM configuration message.'); const value = parsed.data; const models = [...new Set(value.models.split(/[\n,]/).map((x) => x.trim()).filter(Boolean))]; const model = value.type === 'test' ? value.model : models[0]; if (!model) return void render('Add at least one model.'); const secretName = 'sqlOrganizer.openaiApiKey'; try { const key = value.apiKey?.trim() || await context.secrets.get(secretName); if (!key) return void render('Enter an API key to test this endpoint. It will be stored only in SecretStorage when you save.'); const provider = new OpenAiProvider({ apiKey: key, model, baseUrl: value.baseUrl, protocol: value.protocol, timeoutMs: 15000 }); if (value.type === 'test') { await provider.testConnection(); return void render('Connection successful.'); } await store.save({ version: 1, baseUrl: value.baseUrl.trim(), apiProtocol: value.protocol, models }); if (value.apiKey?.trim()) await context.secrets.store(secretName, value.apiKey.trim()); await render('Saved globally. API keys are stored only in VS Code SecretStorage.'); } catch (error) { await render(`Connection failed: ${error instanceof Error ? error.message : String(error)}`); } }, undefined, context.subscriptions); await render(); }
}
function html(baseUrl: string, protocol: string, models: string[], notice: string): string { const nonce = crypto.randomUUID(); const esc = (x: string) => x.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!); return `<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'"><style nonce="${nonce}">body{font:14px var(--vscode-font-family);max-width:760px;margin:24px auto}label{display:block;margin:16px 0 6px}input,textarea,select{box-sizing:border-box;width:100%;padding:8px;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border)}textarea{min-height:100px}button{margin:18px 8px 0 0;padding:8px 14px}.notice{min-height:20px;color:var(--vscode-editorInfo-foreground)}</style><body><h1>LLM Configuration</h1><p>Configure one OpenAI-compatible endpoint and one or more models. Advanced generation settings remain in the YAML configuration file.</p><label>Base URL</label><input id="url" placeholder="https://api.openai.com/v1" value="${esc(baseUrl)}"><label>Protocol</label><select id="protocol"><option value="responses" ${protocol === 'responses' ? 'selected' : ''}>OpenAI Responses API</option><option value="chat-completions" ${protocol === 'chat-completions' ? 'selected' : ''}>Chat Completions compatible</option></select><label>Models (one per line or comma-separated)</label><textarea id="models" placeholder="gpt-4.1-mini\ngpt-4.1">${esc(models.join('\n'))}</textarea><label>API Key (optional when already saved)</label><input id="key" type="password" autocomplete="off" placeholder="Stored only in VS Code SecretStorage"><p class="notice">${esc(notice)}</p><button id="test">Test Connection</button><button id="save">Save Configuration</button><script nonce="${nonce}">const v=acquireVsCodeApi(),d=id=>document.getElementById(id),data=()=>({baseUrl:d('url').value,protocol:d('protocol').value,models:d('models').value,apiKey:d('key').value});d('test').onclick=()=>{const x=data(),m=x.models.split(/[\\n,]/).map(s=>s.trim()).find(Boolean);v.postMessage({...x,type:'test',model:m||''})};d('save').onclick=()=>v.postMessage({...data(),type:'save'});</script></body>`; }
