import * as vscode from 'vscode';
import { OrganizerConfig } from '../config/config';
import { ClassificationRecord, SqlInventoryItem } from '../domain/models';
import { redactSql } from '../scanner/sqlRedactor';
import { sha256 } from '../scanner/sqlAnalyzer';
import { Repository } from '../storage/repository';
import { AiProvider } from './aiProvider';
import { classificationSchema } from './responseValidator';
export class ClassificationService { constructor(private readonly root: vscode.Uri, private readonly config: OrganizerConfig, private readonly repository: Repository, private readonly provider: AiProvider) {} async analyze(items: SqlInventoryItem[], token?: vscode.CancellationToken): Promise<void> { const records = await this.repository.classifications(); const cache = new Map(records.map((record) => [record.cacheKey, record])); for (const item of items) { if (token?.isCancellationRequested || item.warnings.includes('file-too-large')) break; const key = sha256(`${item.rawHash}|v1|${JSON.stringify(this.config.taxonomy.categories)}|${this.config.ai.model}`); const cached = cache.get(key); if (cached) { item.classificationStatus = 'analyzed'; continue; } try { const sql = Buffer.from(await vscode.workspace.fs.readFile(vscode.Uri.parse(item.uri))).toString('utf8'); const classification = classificationSchema.parse(await this.provider.classify({ relativePath: item.relativePath, sizeBytes: item.sizeBytes, operation: item.operation, dialectHint: item.dialectHint, tables: item.tables, parameters: item.parameters, redactedSql: redactSql(sql).slice(0, this.config.ai.maxSqlChars), categories: this.config.taxonomy.categories })); const record: ClassificationRecord = { itemId: item.id, cacheKey: key, classification, analyzedAt: new Date().toISOString() }; records.push(record); cache.set(key, record); item.classificationStatus = 'analyzed'; } catch { item.classificationStatus = 'analysis-error'; } } await this.repository.saveClassifications(records); await this.repository.saveInventory(items); } }
