import { AiProvider, ClassificationInput } from './aiProvider';
import { SqlClassification } from '../domain/models';
export class FakeAiProvider implements AiProvider { public calls = 0; async classify(input: ClassificationInput): Promise<SqlClassification> { this.calls++; return { category: input.categories.includes('unknown') ? 'unknown' : input.categories[0], operation: input.operation, dialect: input.dialectHint, purpose: 'Test classification', suggestedFilename: 'classified-sql.sql', tables: input.tables, parameters: input.parameters, risk: input.operation === 'SELECT' ? 'read-only' : 'unknown', riskReasons: [], confidence: .5, reviewNotes: ['Generated by fake provider'] }; } }
export class InvalidSchemaAiProvider implements AiProvider { async classify(): Promise<SqlClassification> { return {} as SqlClassification; } }
export class TimeoutAiProvider implements AiProvider { async classify(): Promise<SqlClassification> { return new Promise(() => undefined); } }
export class RateLimitAiProvider implements AiProvider { async classify(): Promise<SqlClassification> { throw new Error('rate limit'); } }
